// src/data.js

export const kamus = {
  id: {
    title: "ZENTRYX",
    menuHome: "Beranda", menuActivities: "Aktivitas", dropTasks: "Tugas", dropEvents: "Acara",
    dropCalls: "Panggilan Telepon", dropCalendar: "Kalender", menuShipping: "Pengiriman",
    dropFulfill: "Pemenuhan Pesanan", dropPickPack: "Pick, Pack, & Ship", dropLabels: "Cetak Label Resi",
    dropManifests: "Manifes Pengiriman", menuReceiving: "Penerimaan", dropReceivePO: "Terima Purchase Order",
    dropInbound: "Pengiriman Masuk", dropQC: "Inspeksi Kualitas (QC)", dropPutaway: "Tugas Penempatan Rak",
    menuInventory: "Inventaris", menuReports: "Laporan", dropDailyRep: "Laporan Logistik Harian",
    dropInvVal: "Valuasi Nilai Inventaris", dropShipRecLogs: "Log Pengiriman & Penerimaan",
    dropCarrierPerf: "Performa Kurir", menuAnalytics: "Analitik", dropSupplyChain: "Dashboard Rantai Pasok",
    dropFillRate: "Analisis Tingkat Pemenuhan", dropDemandTrend: "Tren Permintaan", dropCostAnalysis: "Analisis Biaya Operasional",
    menuDocuments: "Dokumen", dropBOL: "Bill of Lading (BOL)", dropPackingSlips: "Surat Jalan / Packing Slip",
    dropInvoices: "Faktur Komersial", dropCompliance: "Dokumen Kepatuhan", menuSetup: "Pengaturan",
    dropCompanyInfo: "Informasi Perusahaan", dropRolesPerms: "Peran & Izin Pengguna", dropWhseLayout: "Manajemen Layout Gudang",
    dropPrintSettings: "Pengaturan Pencetakan", menuProcurement: "Pengadaan", dropRequisitions: "Permintaan Barang",
    dropPO: "Pesanan Pembelian (PO)", dropVendorMgmt: "Manajemen Pemasok", dropRFQ: "Permintaan Penawaran (RFQ)",
    menuDemand: "Perencanaan Permintaan", dropDemandPlans: "Rencana Permintaan Barang", dropSupplyPlans: "Rencana Pasokan Barang",
    dropSafetyStock: "Kalkulasi Stok Aman", menuApps: "Aplikasi Zentryx", dropMarketplace: "Integrasi Toko Online",
    dropERP: "Koneksi ke Sistem Keuangan", dropScanner: "Pengaturan Scanner Barcode", menuSupport: "Dukungan",
    dropHelpCenter: "Pusat Bantuan", dropTicket: "Buat Tiket Bantuan", dropStatus: "Status Server Sistem",
    dropInvOverview: "Ringkasan Inventaris", dropMfg: "Manufaktur", dropLists: "Daftar",
    dropSchedule: "Manajemen Jadwal", dropOther: "Lainnya", dropEngineering: "Rekayasa",
    dropItems: "Barang", dropUOM: "Satuan Ukur", dropBins: "Rak (Bin)", dropShipItems: "Barang Pengiriman",
    dropLocations: "Lokasi", dropLandedCost: "Pemetaan Template Biaya Bongkar", dropNew: "Baru", dropSearch: "Cari",
    remTitle: "Pengingat", remItem1: "Barang untuk Dipesan", remItem2: "Peringatan Perencanaan - Kuantitas di Bawah Batas...",
    kpiTitle: "Meteran KPI", qsTitle: "Pencarian Cepat", qsSearchLabel: "CARI", qsSearchForLabel: "CARI BERDASARKAN",
    qsBtn: "Cari", qsOpt1: "Nama/ID Barang", qsOpt2: "SKU / Barcode", qsOpt3: "Purchase Order (PO)",
    qsOpt4: "Lokasi / Bin", settingsTitle: "Pengaturan", setLink1: "Personalisasi Dashboard",
    setLink2: "Atur Preferensi", setLink3: "Publikasikan Dashboard", setLink4: "Ubah Email",
    setLink5: "Ubah Kata Sandi", setLink6: "Perbarui Pertanyaan Keamanan", invTitle: "Inventaris",
    invCard1: "NILAI INVENTARIS", invCard2: "PERPUTARAN INVENTARIS", invCard3: "HARI INVENTARIS TERSEDIA",
    colInd: "INDIKATOR", colToday: "HARI INI", colWeek: "MINGGU INI (WTD)", colMonth: "BULAN INI (MTD)",
    topItemsTitle: "15 Barang Terlaris Berdasarkan Kuantitas", topItemsDropdown: "bulan ini",
    topItemsEmpty1: "Tidak ada konten", topItemsEmpty2: "Tidak ada data yang tersedia untuk portlet ini.",
    atsTitle: "Tersedia untuk Dijual", atsName: "NAMA", atsLocation: "LOKASI", atsLocAll: "- Semua -",
    atsType: "TIPE", atsTypeInv: "Barang Inventaris", atsUPC: "UPC", chart1Title: "Tren Tingkat Pemenuhan - VPI Bulanan",
    chart1Drop: "Bulanan", chart1Legend1: "Tingkat Pemenuhan", chart1Legend2: "Rata-rata Bergerak",
    chart2Title: "Tren Inventaris Mingguan", niTitle: "New Item", niCol1: "ITEM TYPE", niCol2: "MATRIX ITEM ASSISTANT",
    niCol3: "CREATE MATRIX ITEMS", niAsst: "Matrix Item Assistant", niCreate: "Create Matrix Items",
    taskTitle: "Daftar Tugas Harian", taskCol1: "ID TUGAS", taskCol2: "DESKRIPSI", taskCol3: "PRIORITAS",
    taskCol4: "STATUS", taskCol5: "TENGGAT WAKTU", taskBtn: "Tugas Baru",
    taskSearch: "Cari tugas...", taskAllStatuses: "Semua Status", taskAllPriorities: "Semua Prioritas",
    taskSortDue: "Urutkan berdasarkan Tenggat", taskSortPriority: "Urutkan berdasarkan Prioritas", taskSortStatus: "Urutkan berdasarkan Status",
    taskAscending: "Naik", taskDescending: "Turun", taskActions: "Aksi",
    taskConfirmDelete: "Hapus tugas ini?", taskConfirmBulkComplete: "Tandai tugas terpilih sebagai selesai?", taskConfirmBulkDelete: "Hapus tugas terpilih?",
    taskBulkComplete: "Bulk Complete", taskBulkDelete: "Bulk Delete", taskSelectedCount: "item dipilih",
    taskUndo: "Batal", taskMarkDone: "Selesai", taskEdit: "Ubah", taskDelete: "Hapus",
    taskNewTitle: "Tugas Baru", taskEditTitle: "Ubah Tugas", taskModalSubtitle: "Jaga tim tetap selaras dengan tenggat dan prioritas.",
    taskCloseLabel: "Tutup modal tugas", taskDescriptionPlaceholder: "Masukkan deskripsi tugas", taskNotesLabel: "Catatan",
    taskNotesPlaceholder: "Rincian atau instruksi opsional", taskPriorityLabel: "Prioritas", taskCreatedLabel: "Dibuat",
    taskCancel: "Batal", taskSave: "Simpan Tugas", taskDescriptionRequired: "Deskripsi tugas harus diisi.", taskDueDateRequired: "Silakan pilih tanggal tenggat.",
    taskNoMatch: "Belum ada tugas yang sesuai.", taskNoMatchSub: "Gunakan filter atau tambahkan tugas baru untuk memulai.",
    taskSelectAll: "Pilih semua tugas", taskSelectRow: "Pilih tugas",
    callTitle: "Log Panggilan Telepon", callNew: "Catat Panggilan", callSearch: "Cari panggilan...", callAllStatuses: "Semua Status",
    callColId: "ID PANGGILAN", callColContact: "KONTAK", callColSubject: "SUBJEK", callColDate: "TANGGAL", callColStatus: "STATUS", callActions: "AKSI",
    callStatusScheduled: "Dijadwalkan", callStatusCompleted: "Selesai", callStatusMissed: "Lewat",
    callConfirmDelete: "Hapus panggilan ini?", callRequiredContactSubject: "Kontak dan subjek harus diisi.", callIcsMissingDate: "Tanggal dan waktu diperlukan untuk ekspor ICS.",
    callEdit: "Ubah", callDelete: "Hapus", callEmail: "Email", callIcsBtn: "ICS",
    callCreateTitle: "Catat Panggilan Baru", callEditTitle: "Ubah Panggilan", callModalSubtitle: "Tambahkan atau perbarui catatan panggilan dengan opsi email dan ekspor kalender.",
    callCloseLabel: "Tutup modal panggilan", callContactLabel: "Kontak", callSubjectLabel: "Subjek", callDateLabel: "Tanggal", callTimeLabel: "Waktu", callStatusLabel: "Status",
    callCancel: "Batal", callSave: "Simpan Panggilan",
    calendarTitle: "Kalender - Juni 2026", calendarAddBtn: "Tambah Jadwal", calendarToday: "Hari Ini", calendarPrev: "Sebelumnya", calendarNext: "Berikutnya",
    calendarSearch: "Cari acara...", calendarNoEvents: "Tidak ada acara", calendarEmail: "Email", calendarGCal: "G-Cal", calendarEdit: "Ubah", calendarDelete: "Hapus",
    calendarIcs: "ICS", calendarRequiredFields: "Judul & Tanggal wajib diisi!", calendarDeleteConfirm: "Hapus acara ini?", calendarEventTitleRequired: "Judul acara diperlukan.",
    calendarIcsMissingDate: "Tanggal diperlukan untuk ekspor ICS.",
    eventTitle: "Acara Mendatang", eventNew: "Acara Baru", eventCol1: "ID ACARA", eventCol2: "JUDUL", eventCol3: "TANGGAL", eventCol4: "WAKTU", eventCol5: "LOKASI",
    eventActions: "Aksi", eventCreateTitle: "Buat Acara Baru", eventEditTitle: "Ubah Acara", eventModalSubtitle: "Catat acara logistik penting dan bagikan dengan tim.",
    eventCloseLabel: "Tutup modal acara", eventTitleLabel: "Judul Acara", eventTitlePlaceholder: "Judul Acara", eventDateLabel: "Tanggal", eventTimeLabel: "Waktu",
    eventLocationLabel: "Lokasi", eventLocationPlaceholder: "Lokasi", eventCancel: "Batal", eventSave: "Simpan Acara"
  },
  en: {
    title: "ZENTRYX", menuHome: "Home", menuActivities: "Activities", dropTasks: "Tasks", dropEvents: "Events",
    dropCalls: "Phone Calls", dropCalendar: "Calendar", menuShipping: "Shipping", dropFulfill: "Fulfill Orders",
    dropPickPack: "Pick, Pack, & Ship", dropLabels: "Generate Labels", dropManifests: "Shipping Manifests",
    menuReceiving: "Receiving", dropReceivePO: "Receive Purchase Orders", dropInbound: "Inbound Shipments",
    dropQC: "Quality Inspections", dropPutaway: "Putaway Tasks", menuInventory: "Inventory", menuReports: "Reports",
    dropDailyRep: "Daily Logistics Report", dropInvVal: "Inventory Valuation", dropShipRecLogs: "Shipping & Receiving Logs",
    dropCarrierPerf: "Carrier Performance", menuAnalytics: "Analytics", dropSupplyChain: "Supply Chain Dashboard",
    dropFillRate: "Fill Rate Analysis", dropDemandTrend: "Demand Trends", dropCostAnalysis: "Cost Analysis",
    menuDocuments: "Documents", dropBOL: "Bill of Lading (BOL)", dropPackingSlips: "Packing Slips",
    dropInvoices: "Commercial Invoices", dropCompliance: "Compliance Documents", menuSetup: "Setup",
    dropCompanyInfo: "Company Information", dropRolesPerms: "User Roles & Permissions", dropWhseLayout: "Warehouse Layout Management",
    dropPrintSettings: "Printing Settings", menuProcurement: "Procurement", dropRequisitions: "Requisitions",
    dropPO: "Purchase Orders (PO)", dropVendorMgmt: "Vendor Management", dropRFQ: "Request for Quote (RFQ)",
    menuDemand: "Demand Planning", dropDemandPlans: "Item Demand Plans", dropSupplyPlans: "Item Supply Plans",
    dropSafetyStock: "Safety Stock Calculations", menuApps: "Zentryx Apps", dropMarketplace: "Marketplace Integrations",
    dropERP: "ERP Integrations", dropScanner: "Barcode Scanner Setup", menuSupport: "Support",
    dropHelpCenter: "Help Center / Knowledge Base", dropTicket: "Submit a Ticket", dropStatus: "System Status",
    dropInvOverview: "Inventory Overview", dropMfg: "Manufacturing", dropLists: "Lists",
    dropSchedule: "Schedule Management", dropOther: "Other", dropEngineering: "Engineering",
    dropItems: "Items", dropUOM: "Units Of Measure", dropBins: "Bins", dropShipItems: "Shipping Items",
    dropLocations: "Locations", dropLandedCost: "Landed Cost Template Mapping", dropNew: "New", dropSearch: "Search",
    remTitle: "Reminders", remItem1: "Items to Order", remItem2: "Planning Alert - Quantity On Hand is Below...",
    kpiTitle: "KPI Meter", qsTitle: "Quick Search", qsSearchLabel: "SEARCH", qsSearchForLabel: "SEARCH FOR",
    qsBtn: "Search", qsOpt1: "Name/ID", qsOpt2: "SKU / Barcode", qsOpt3: "Purchase Order (PO)",
    qsOpt4: "Location / Bin", settingsTitle: "Settings", setLink1: "Personalize Dashboard",
    setLink2: "Set Preferences", setLink3: "Publish Dashboard", setLink4: "Change Email",
    setLink5: "Change Password", setLink6: "Update Security Questions", invTitle: "Inventory",
    invCard1: "INVENTORY VALUE", invCard2: "INVENTORY TURNOVER", invCard3: "DAYS INVENTORY ON HAND",
    colInd: "INDICATOR", colToday: "TODAY", colWeek: "THIS WTD", colMonth: "THIS MTD",
    topItemsTitle: "Top 15 Items By Qty Sold (This Month)", topItemsDropdown: "this month to date",
    topItemsEmpty1: "No content", topItemsEmpty2: "No data available for this portlet.",
    atsTitle: "Available to Sell", atsName: "NAME", atsLocation: "LOCATION", atsLocAll: "- All -",
    atsType: "TYPE", atsTypeInv: "Inventory Item", atsUPC: "UPC", chart1Title: "Monthly VPI - Fill Rates Trend",
    chart1Drop: "Monthly", chart1Legend1: "VPI - Fill Rates", chart1Legend2: "Moving Average",
    chart2Title: "Weekly Inventory Trend", niTitle: "New Item", niCol1: "ITEM TYPE", niCol2: "MATRIX ITEM ASSISTANT",
    niCol3: "CREATE MATRIX ITEMS", niAsst: "Matrix Item Assistant", niCreate: "Create Matrix Items",
    taskTitle: "Daily Task List", taskCol1: "TASK ID", taskCol2: "DESCRIPTION", taskCol3: "PRIORITY",
    taskCol4: "STATUS", taskCol5: "DUE DATE", taskBtn: "New Task",
    taskSearch: "Search tasks...", taskAllStatuses: "All Statuses", taskAllPriorities: "All Priorities",
    taskSortDue: "Sort by Due Date", taskSortPriority: "Sort by Priority", taskSortStatus: "Sort by Status",
    taskAscending: "Ascending", taskDescending: "Descending", taskActions: "Actions",
    taskConfirmDelete: "Delete this task?", taskConfirmBulkComplete: "Mark selected tasks complete?", taskConfirmBulkDelete: "Delete selected tasks?",
    taskBulkComplete: "Bulk Complete", taskBulkDelete: "Bulk Delete", taskSelectedCount: "selected items",
    taskUndo: "Undo", taskMarkDone: "Mark Done", taskEdit: "Edit", taskDelete: "Delete",
    taskNewTitle: "New Task", taskEditTitle: "Edit Task", taskModalSubtitle: "Keep the team aligned with due dates and priorities.",
    taskCloseLabel: "Close task modal", taskDescriptionPlaceholder: "Enter task description", taskNotesLabel: "Notes",
    taskNotesPlaceholder: "Optional details or instructions", taskPriorityLabel: "Priority", taskCreatedLabel: "Created",
    taskCancel: "Cancel", taskSave: "Save Task", taskDescriptionRequired: "Task description is required.", taskDueDateRequired: "Please choose a due date.",
    taskNoMatch: "No matching tasks yet.", taskNoMatchSub: "Use the filters or add a new task to get started.",
    taskSelectAll: "Select all tasks", taskSelectRow: "Select task",
    callTitle: "Phone Calls Log", callNew: "Log Call", callSearch: "Search calls...", callAllStatuses: "All Statuses",
    callColId: "CALL ID", callColContact: "CONTACT", callColSubject: "SUBJECT", callColDate: "DATE", callColStatus: "STATUS", callActions: "ACTIONS",
    callStatusScheduled: "Scheduled", callStatusCompleted: "Completed", callStatusMissed: "Missed",
    callConfirmDelete: "Delete this call?", callRequiredContactSubject: "Contact and subject are required.", callIcsMissingDate: "Date and time are required to export the ICS file.",
    callEdit: "Edit", callDelete: "Delete", callEmail: "Email", callIcsBtn: "ICS",
    callCreateTitle: "Log New Call", callEditTitle: "Edit Call", callModalSubtitle: "Add or update a call record with email and calendar export options.",
    callCloseLabel: "Close call modal", callContactLabel: "Contact", callSubjectLabel: "Subject", callDateLabel: "Date", callTimeLabel: "Time", callStatusLabel: "Status",
    callCancel: "Cancel", callSave: "Save Call",
    calendarTitle: "Calendar - June 2026", calendarAddBtn: "Add Schedule", calendarToday: "Today", calendarPrev: "Previous", calendarNext: "Next",
    calendarSearch: "Search events...", calendarNoEvents: "No events", calendarEmail: "Email", calendarGCal: "G-Cal", calendarEdit: "Edit", calendarDelete: "Delete",
    calendarIcs: "ICS", calendarRequiredFields: "Title & Date required!", calendarDeleteConfirm: "Delete this event?", calendarEventTitleRequired: "Event title is required.",
    calendarIcsMissingDate: "Date is required to export ICS.",
    eventTitle: "Upcoming Events", eventNew: "New Event", eventCol1: "EVENT ID", eventCol2: "TITLE", eventCol3: "DATE", eventCol4: "TIME", eventCol5: "LOCATION",
    eventActions: "Actions", eventCreateTitle: "Create New Event", eventEditTitle: "Edit Event", eventModalSubtitle: "Capture key logistics events and share them with the team.",
    eventCloseLabel: "Close event modal", eventTitleLabel: "Event Title", eventTitlePlaceholder: "Event Title", eventDateLabel: "Date", eventTimeLabel: "Time",
    eventLocationLabel: "Location", eventLocationPlaceholder: "Location", eventCancel: "Cancel", eventSave: "Save Event"
  }
};

export const getItemTypes = (bahasa) => [
  { name: bahasa === 'en' ? "Description" : "Deskripsi", isSub: false, links: false },
  { name: bahasa === 'en' ? "Discount" : "Diskon", isSub: false, links: false },
  { name: bahasa === 'en' ? "Inventory Item" : "Barang Inventaris", isSub: false, links: true },
  { name: bahasa === 'en' ? "Lot Numbered" : "Bernomor Lot", isSub: true, links: true },
  { name: bahasa === 'en' ? "Serialized" : "Berseri", isSub: true, links: true },
  { name: bahasa === 'en' ? "Item Group" : "Grup Barang", isSub: false, links: false },
  { name: bahasa === 'en' ? "Kit/Package" : "Kit/Paket", isSub: false, links: false },
  { name: bahasa === 'en' ? "Markup" : "Markup", isSub: false, links: false },
  { name: bahasa === 'en' ? "Non-inventory Item" : "Barang Non-inventaris", isSub: false, links: false },
  { name: bahasa === 'en' ? "For Purchase" : "Untuk Dibeli", isSub: true, links: true },
  { name: bahasa === 'en' ? "For Resale" : "Untuk Dijual Kembali", isSub: true, links: true },
  { name: bahasa === 'en' ? "For Sale" : "Untuk Dijual", isSub: true, links: true },
  { name: bahasa === 'en' ? "Other Charge" : "Biaya Lainnya", isSub: false, links: false },
  { name: bahasa === 'en' ? "Payment" : "Pembayaran", isSub: false, links: false },
  { name: bahasa === 'en' ? "Service" : "Layanan", isSub: false, links: false },
  { name: bahasa === 'en' ? "Subtotal" : "Subtotal", isSub: false, links: false }
];

export const getPOData = () => [
  { id: "PO-1001", supplier: "PT Foxconn", eta: "2026-06-15", status: "Arrived at Dock" },
  { id: "PO-1002", supplier: "NVIDIA Corp", eta: "2026-06-16", status: "Pending" }
];

export const getSalesOrderData = () => [
  { id: "SO-2001", customer: "Kementerian Perhubungan", date: "15 Jun 2026", status: "Ready to Pick" },
  { id: "SO-2002", customer: "PT Maju Bersama", date: "16 Jun 2026", status: "Ready to Pick" }
];    

export const dashboardStats = {
  invValue: "1,315,575",
  invTurnover: "1.2",
  daysOnHand: "2,894,263.92",
  reminders: { itemsToOrder: 5, planningAlerts: 110 }
};

export const getTaskData = (bahasa) => {
  const getYearMonthPrefix = () => {
    const d = new Date();
    return `${d.getFullYear().toString().slice(-2)}${String(d.getMonth() + 1).padStart(2, '0')}`;
  };
  const todayStr = new Date().toISOString().slice(0, 10);
  
  return [
    { 
      id: `TSK-ARS-${getYearMonthPrefix()}-007`, 
      type: 'Putaway', 
      desc: 'Putaway 12 Pallets of MCU Gen 3 from PO-1001', 
      zone: 'Clean Room A', 
      assignee: 'Budi (AGV Operator)', 
      priority: 'Medium', 
      status: 'Not Started', 
      currentStage: 'Awaiting Authorization', 
      isLocked: true, 
      dependency: 'QA Clearance Required', 
      sku: 'SKU-ARS-MCU03',
      refId: 'PO-1001',
      qty: 120,
      dueDate: todayStr, 
      notes: 'System locked until QA team approves inbound batch.', 
      createdAt: new Date().toISOString() 
    },
    { 
      id: `TSK-ARS-${getYearMonthPrefix()}-001`, 
      type: 'Picking', 
      desc: 'Pick 50 LFP Battery Packs for Assembly Line 1', 
      zone: 'Zone B (Cold Storage)', 
      assignee: 'Agus (Forklift)', 
      priority: 'Critical', 
      status: 'In Progress', 
      currentStage: 'Scanning Location', 
      isLocked: false, 
      dependency: 'None', 
      sku: 'BATT-LFP-75K',
      qty: 50,
      dueDate: todayStr, 
      notes: 'Handle with care. Follow ESD protocol.', 
      createdAt: new Date(Date.now() - 1200000).toISOString(), 
      pickingStartAt: new Date(Date.now() - 300000).toISOString() 
    }
  ];
};